language: ruby

rvm:
  - 2.0.0
  - 2.1.8
  - 2.2.4
  - 2.3.0

gemfile:
  - Gemfile
  - gemfiles/rails_5_beta4.gemfile

matrix:
  exclude:
    - rvm: 2.0.0
      gemfile: gemfiles/rails_5_beta4.gemfile
    - rvm: 2.1.8
      gemfile: gemfiles/rails_5_beta4.gemfile

before_install:
  - gem update bundler

script:
  - bundle exec rspec
